### ISSUE TITLE
Dynamically generated matrix

### ISSUE THREAD

**Issue by pbrisbin** [freckle/stack-action#17]
I'm not sure if this is truly an Issue on this project, but I wanted to capture it somewhere and this seems like the best context within which to place it.

---

One super common use-case for this action is to build across all your `stack-*.yaml` files,

```yaml
jobs:
  test:
    # ...

    strategy:
      matrix:
        stack-yaml:
          - stack-nightly.yaml   # ghc-9.0
          - stack.yaml           # ghc-9.0
          - stack-lts-18.28.yaml # ghc-8.10
          - stack-lts-16.31.yaml # ghc-8.8
          - stack-lts-14.27.yaml # ghc-8.6
          - stack-lts-12.26.yaml # ghc-8.4
          - stack-persistent-2.14.yaml
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - uses: freckle/stack-cache-action@v2
        with:
          stack-yaml: ${{ matrix.stack-yaml }}
      - uses: freckle/stack-action@v3
        with:
          stack-yaml: ${{ matrix.stack-yaml }}
```

Maintaining this `matrix` is busy-work and error-prone. Thankfully, GitHub cleanly supports dynamic matrices by passing JSON through the output/interpolation system. For example:

```yaml
jobs:
  generate-matrix:
    # ...

    steps:
      - id: generate
        run: |
          {
            echo 'stack-yamls<<EOM'
            find -maxdepth 1 -name 'stack*.yaml' -printf '["%f"]\n' | jq --slurp 'flatten'
            echo 'EOM'
          } >>"$GITHUB_OUTPUT"

    outputs:
      stack-yamls: ${{ steps.generate.outputs.stack-yamls }}

  test:
    needs: generate-matrix

    strategy:
      matrix:
        stack-yaml: ${{ fromJSON(needs.generate-matrix.outputs.stack-yamls) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - uses: freckle/stack-cache-action@v2
        with:
          stack-yaml: ${{ matrix.stack-yaml }}
      - uses: freckle/stack-action@v3
        with:
          stack-yaml: ${{ matrix.stack-yaml }}
```

For context,

```console
find -maxdepth 1 -name 'stack*.yaml' -printf '["%f"]\n' | jq --slurp 'flatten'
```

Outputs:

```json
[
  "stack-lts-14.27.yaml",
  "stack-persistent-2.14.yaml",
  "stack-lts-12.26.yaml",
  "stack-nightly.yaml",
  "stack-lts-18.28.yaml",
  "stack.yaml",
  "stack-lts-16.31.yaml"
]
```

Maybe this is just something we should document on the README, since it's relatively easy for users to just do themselves, but I wonder if we can somehow offer the "generate" command either as part of this action or as a separate action. There can be complexities beyond the happy-path case, which means both a) there's value we could provide in such an action but also b) maybe it's best to leave users to do the specific things they need themselves.

:thinking:
