### ISSUE TITLE
Stack version correspondence

### ISSUE THREAD

**Issue by Divesh-Otwani** [freckle/stack-action#207]
I've found that when you set the stack version in your `stack.yaml` you get a "missing directory" error. We know the `working-directory` is correct because this used to work fine until some update.

stack.yaml
```
snapshot:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/23/9.yaml

packages:
- .

require-stack-version: "==3.5.1"
```

In the CI file:
```
name: Haskell CI

on:
  push:
    branches:
      - '**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: freckle/stack-action@fdcad1f184efc94655846399f9ecae6b810b3924 # v5
      with:
        working-directory: haskell-project
        stack-yaml: stack.yaml

```
